### ISSUE TITLE
Warning: The `set-output` command is deprecated

### ISSUE THREAD

**Issue by Roberto-Gentili** [egor-tensin/setup-mingw#9]
On this configuration:
<br/>
```yaml
uses: egor-tensin/setup-mingw@v2
with:
    platform: x86
```
<br/>
This warning is printed:

```Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```
